import { rgbaArray } from "react-native-svg";

export type TIcon =
  | "ArrowDown"
  | "ArrowBack"
  | "ArrowForward"
  | "ArrowUpLight"
  | "ArrowDownLight"
  | "ArrowBackLight"
  | "ArrowRightLight"
  | "ArrowChange"
  | "Info"
  | "Email"
  | "Menu"
  | "Edit"
  | "Google"
  | "Facebook"
  | "LinkedIn"
  | "Apple"
  | "Done"
  | "Mic"
  | "MoreVert"
  | "CompassWithCircles"
  | "Delete"
  | "Circle"
  | "Market"
  | "Clock"
  | "Bubble"
  | "Eve"
  | "Dot"
  | "FavClothingStyle"
  | "AssessMent"
  | "BatteryRight"
  | "BookMark"
  | "Cancel"
  | "DirectionsCar"
  | "Domain"
  | "ExitApp"
  | "Fider"
  | "Flash"
  | "Gps"
  | "History"
  | "Home"
  | "Map"
  | "Nature"
  | "Navigation"
  | "Person"
  | "Plus"
  | "Polymer"
  | "Position"
  | "Room"
  | "Search"
  | "Setting"
  | "Spa"
  | "Speed"
  | "Star"
  | "Timeline"
  | "Calendar"
  | "EvStation"
  | "Filter"
  | "Clear"
  | "CarAvailability"
  | "CarCO2"
  | "CarColor"
  | "CarDoors"
  | "CarFuel"
  | "CarHorsepower"
  | "CarMaxSpeed"
  | "CarModel"
  | "CarPlate"
  | "CarSits"
  | "CarType"
  | "CarIdle"
  | "CarIdleTimeIn"
  | "CarMaxRange"
  | "CarMinRange"
  | "CarMinTripLength"
  | "CarDialyAvg"
  | "CarTimeIn"
  | "CarWeeklyAvg"
  | "Error";

export interface ISVG {
  fill: string | number | rgbaArray;
  stroke: string | number | rgbaArray;
}
